// Mocks generated by Mockito 5.3.2 from annotations
// in motis_mitfahr_app/test/util/mocks/request_processor.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import 'request_processor.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProcessorResult_0 extends _i1.SmartFake implements _i2.ProcessorResult {
  _FakeProcessorResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RequestProcessor].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestProcessor extends _i1.Mock implements _i2.RequestProcessor {
  MockRequestProcessor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProcessorResult process(
    String? url, {
    String? method,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #process,
          [url],
          {
            #method: method,
            #body: body,
          },
        ),
        returnValue: _FakeProcessorResult_0(
          this,
          Invocation.method(
            #process,
            [url],
            {
              #method: method,
              #body: body,
            },
          ),
        ),
      ) as _i2.ProcessorResult);
}
