// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_app/test/driveTest.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_app/util/supabase.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupabaseManagerManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseManagerManager extends _i1.Mock implements _i3.SupabaseManagerManager {
  MockSupabaseManagerManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient getSupabaseClient() => (super.noSuchMethod(
        Invocation.method(
          #get_supabase_client,
          [],
        ),
        returnValue: _FakeSupabaseClient_0(
          this,
          Invocation.method(
            #get_supabase_client,
            [],
          ),
        ),
      ) as _i2.SupabaseClient);
}
